version: "3"
volumes:
  postgres_volume:

services:
  client_service:
    container_name: client_service
    build:
      dockerfile : Dockerfile
      context: client_service
    ports:
      - 90:90
    command: uvicorn app.main:app --host 0.0.0.0 --port 90
    env_file:
      - client_service/.env
    volumes:
    - ./client_service/:/client_service/
    depends_on:
      - postgres

  banker_service:
    container_name: banker_service
    build:
      dockerfile: Dockerfile
      context: banker_service
    ports:
      - 91:90
    command: uvicorn app.main:app --host 0.0.0.0 --port 90
    env_file:
      - banker_service/.env
    volumes:
      - ./banker_service/:/banker_service/
    depends_on:
        - postgres

  postgres:
    container_name: postgres_banking
    image: postgres:11
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - client_service/.env
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - banker_service
      - client_service